apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment
  namespace: kubernetes-cluster-kamal02
  labels:
    app: dotnet-app-master
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dotnet-app-master
  template:
    metadata:
      labels:
        app: dotnet-app-master
    spec:
      containers:
        - name: dotnet-app-master
          image: kamalmittal2020/i-kamal02-master:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "350Mi"
              cpu: "350m"
            limits:
              memory: "500Mi"
              cpu: "500m"



