apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-master
  namespace: kubernetes-cluster-kamal02
spec:
  type: NodePort
  selector:
    app: dotnet-app-master
  ports:
    - protocol: TCP
      nodePort: 30157
      port: 80
      targetPort: 8088